name: flutter_google_places_sdk
description: A Flutter plugin for google places sdk that uses the native libraries on each platform
version: 0.3.5
homepage: https://github.com/matanshukry/flutter_google_places_sdk/tree/master/flutter_google_places_sdk

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_google_places_sdk_platform_interface:
    git:
      url: https://github.com/wopta/flutter_google_places_sdk.git
      path: flutter_google_places_sdk_platform_interface
  flutter_google_places_sdk_ios:
    git:
      url: https://github.com/wopta/flutter_google_places_sdk.git
      path: flutter_google_places_sdk_ios
  flutter_google_places_sdk_web:
    git:
      url: https://github.com/wopta/flutter_google_places_sdk.git
      path: flutter_google_places_sdk_web
  flutter_google_places_sdk_android:
    git:
      url: https://github.com/wopta/flutter_google_places_sdk.git
      path: flutter_google_places_sdk_android
  flutter_google_places_sdk_windows:
    git:
      url: https://github.com/wopta/flutter_google_places_sdk.git
      path: flutter_google_places_sdk_windows
  flutter_google_places_sdk_linux:
    git:
      url: https://github.com/wopta/flutter_google_places_sdk.git
      path: flutter_google_places_sdk_linux
  flutter_google_places_sdk_macos:
    git:
      url: https://github.com/wopta/flutter_google_places_sdk.git
      path: flutter_google_places_sdk_macos

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_google_places_sdk_android
      ios:
        default_package: flutter_google_places_sdk_ios
      web:
        default_package: flutter_google_places_sdk_web
      windows:
        default_package: flutter_google_places_sdk_windows
      linux:
        default_package: flutter_google_places_sdk_linux
      macos:
        default_package: flutter_google_places_sdk_macos
