name: flutter_google_places_sdk_windows
description: The windows implementation of Flutter plugin for google places sdk
version: 0.1.2
homepage: https://github.com/matanshukry/flutter_google_places_sdk/tree/master/flutter_google_places_sdk_windows

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_google_places_sdk_platform_interface:
    path: ../flutter_google_places_sdk_platform_interface
  flutter_google_places_sdk_http:
    path: ../flutter_google_places_sdk_http

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  plugin:
    implements: flutter_google_places_sdk
    platforms:
      windows:
        fileName: flutter_google_places_sdk_windows.dart
        dartPluginClass: FlutterGooglePlacesSdkWindowsPlugin
